print("This is an test check please do not bother to interfere ")
print("Checking again")
print("Silver")
print("platinum")
print("joker")
print("eleven and queen added")
print("Cop Added")
print("Hi this is a check")
print("check again part 3")
print("24 added to the list.")
